server:
  port: 7005

spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  mapper-locations: classpath:mapper/*mapper.xml

logging:
  level:
    com.example: debug
  pattern:
    dateformat: YY-MM-dd HH:mm:ss:SSS
