spring:
  profiles: dev
---
server:
  port: 8003

spring:
  profiles: dev
  application:
    name: orderservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-order?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

mybatis-plus:
  mapper-locations: classpath:mapper/*mapper.xml
logging:
  level:
    com.springcloud: debug
  pattern:
    dateformat: YY-MM-dd HH:mm:ss:SSS
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
ribbon:
  eager-load:
    clients:
      - userserivce
    enabled: true
---
server:
  port: 8004

spring:
  profiles: test
  application:
    name: orderservice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-order?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

mybatis-plus:
  mapper-locations: classpath:mapper/*mapper.xml
logging:
  level:
    com.springcloud: debug
  pattern:
    dateformat: YY-MM-dd HH:mm:ss:SSS
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
ribbon:
  eager-load:
    clients:
      - userserivce
    enabled: true